[package]
name = "memorandum"
version = "0.1.0"
authors = ["Jesse B. Miller <jesse@jessebmiller.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
